export const oldData = [
  {
    id: "2DOJU4pz5JyJH1RlVO9u",
    list: [
      {
        description: "Centurion D10 24v PSU + Call Out Fee",
        quantity: "1",
        amount: "195.50",
      },
    ],
    splitCost: 195.5,
    total: 1564,
    invoiceDueDate: "2023-10-31",
    invoiceNumber: "0009",
    invoiceDate: "2023-10-25",
    batchNumber: 9,
    status: "Unpaid",
    complexName: "Yale",
    invoiceTitle: "Main Gate Power Supply Replacement",
  },
  {
    id: "2znkxy3KtzntMQMyn9TB",
    invoiceDate: "2023-11-06",
    status: "Unpaid",
    list: [
      {
        quantity: "1",
        amount: "81.25",
        description: "Trace and Repair of Damaged Cable",
      },
    ],
    invoiceNumber: "0010",
    invoiceTitle: "Repaired Gate Cable",
    complexName: "Cambridge",
    batchNumber: 10,
    invoiceDueDate: "2023-11-30",
    total: 650,
    splitCost: 81.25,
  },
  {
    id: "30hP0uyehpG2OKoFHyhj",
    invoiceDate: "2023-10-11",
    splitCost: 1188,
    invoiceDueDate: "2023-10-31",
    invoiceTitle: "Princeton Reimbursement for Greenbelt Cutting",
    status: "Unpaid",
    invoiceNumber: "0006",
    list: [
      {
        amount: "500",
        quantity: "1",
        description:
          "10M CUTTING THE TREES INCLUDING MACHINE AND LABOUR (DAVID TLB)",
      },
      {
        description:
          "Removing of, cutting & cleaning (veld) at the back of Princeton",
        amount: "688",
        quantity: "1",
      },
    ],
    total: 9504,
    complexName: "Stanford",
    batchNumber: 6,
  },
  {
    id: "3S2eWd67QWppfQ3zVNyF",
    splitCost: 0,
    batchNumber: 3,
    invoiceDate: "2023-08-24",
    complexName: "Princeton",
    invoiceNumber: "0003",
    invoiceTitle:
      "Gate Wheels Replacement & Rack Adjustment Exit Gate + Intercom Airtime Reimbursement",
    invoiceDueDate: "2023-08-31",
    total: 1584,
    status: "Paid",
    list: [
      {
        amount: "167",
        description: "Gate Wheels Replacement & Rack Adjustment Exit Gate",
        quantity: "1",
      },
      {
        description:
          "Princeton Main Gate Intercom Reimbursement (R245 - 1x R200 Airtime + 1x 200 SMS's)",
        quantity: "1",
        amount: "31",
      },
    ],
  },
  {
    id: "3ZslftrYXRwIOyKu8KNc",
    complexName: "UCLA",
    splitCost: 0,
    status: "Paid",
    batchNumber: 4,
    invoiceTitle:
      "The Campus Complex Intercom - Request for Payment Instructions and Invoice",
    total: 2504,
    invoiceDate: "2023-08-25",
    invoiceNumber: "0004",
    list: [
      {
        amount: "313",
        quantity: "1",
        description: "Main Gate Intercom Annual Fee Contribution",
      },
    ],
    invoiceDueDate: "2023-08-31",
  },
  {
    id: "4emZyPRg5LTpMW9NNVGx",
    invoiceDueDate: "2023-07-31",
    splitCost: 0,
    invoiceDate: "2023-07-16",
    invoiceTitle: "Remote Reprogramming + Airtime Contribution",
    complexName: "Yale",
    batchNumber: 2,
    invoiceNumber: "0002",
    list: [
      {
        description:
          "Call Out Fee for Remote Programming - 2 Dates & Overtime. 13 th June 10:00 - 12:00 & 18 th June 18:30 - 19:30",
        quantity: "1",
        amount: "143.75",
      },
      {
        description: "Main Gate Intercom Monthly Airtime Contribution ",
        quantity: "1",
        amount: "200",
      },
      {
        amount: "33.13",
        quantity: "1",
        description:
          "UCLA Main Gate Intercom Reimbursement (R265- 1x R110 Airtime + 1x 200 SMS's)",
      },
      {
        quantity: "1",
        description:
          "Princeton Main Gate Intercom Reimbursement (R245 - 1x R200 Airtime + 1x 200 SMS's)",
        amount: "30.63",
      },
    ],
    status: "Paid",
    total: 3260.08,
  },
  {
    id: "4gsvMHk7IrIp4NlTEmCC",
    invoiceDueDate: "2023-10-31",
    invoiceNumber: "0008",
    status: "Unpaid",
    invoiceDate: "2023-10-25",
    total: 900,
    batchNumber: 8,
    splitCost: 112.5,
    complexName: "NYU",
    invoiceTitle: "Remote Programming - Main Gate",
    list: [
      {
        quantity: "1",
        description:
          "Bentley Security Services - Remote Reprogramming Call Out Fee",
        amount: "112.50",
      },
    ],
  },
  {
    id: "5LB4dnwfXlJZmODPQR8K",
    invoiceDueDate: "2023-11-30",
    batchNumber: 11,
    total: 33991.44,
    complexName: "Cambridge",
    invoiceDate: "2023-11-27",
    splitCost: 4248.93,
    list: [
      {
        description: "EC Security - Main Gate Guarding ",
        amount: "4248.93",
        quantity: "1",
      },
    ],
    invoiceNumber: "0011",
    invoiceTitle: "EC Security ",
    status: "Unpaid",
  },
  {
    id: "5XTkkPuNmFn0uTO2qQyu",
    status: "Paid",
    batchNumber: 1,
    total: 1568,
    complexName: "Oxford",
    invoiceNumber: "0001",
    list: [
      {
        amount: "196",
        description:
          "Gate Wheels Replacement, Rack Adjustment & Pinion Gear Replacement.",
        quantity: "1",
      },
    ],
    splitCost: 0,
    invoiceDueDate: "2023-06-30",
    invoiceDate: "2023-06-10",
    invoiceTitle:
      "Gate Wheels Replacement, Rack Adjustment & Pinion Gear Replacement.",
  },
  {
    id: "60fsK7aFnXUgzotFBtn8",
    invoiceNumber: "0003",
    invoiceDate: "2023-08-24",
    invoiceDueDate: "2023-08-31",
    batchNumber: 3,
    status: "Paid",
    complexName: "UCLA",
    splitCost: 0,
    total: 1584,
    list: [
      {
        amount: "167",
        description: "Gate Wheels Replacement & Rack Adjustment Exit Gate",
        quantity: "1",
      },
      {
        quantity: "1",
        amount: "31",
        description:
          "Princeton Main Gate Intercom Reimbursement (R245 - 1x R200 Airtime + 1x 200 SMS's)",
      },
    ],
    invoiceTitle:
      "Gate Wheels Replacement & Rack Adjustment Exit Gate + Intercom Airtime Reimbursement",
  },
  {
    id: "79Ahm82BWWz2PnZkvgMS",
    batchNumber: 10,
    invoiceDate: "2023-11-06",
    complexName: "Oxford",
    list: [
      {
        amount: "81.25",
        quantity: "1",
        description: "Trace and Repair of Damaged Cable",
      },
    ],
    invoiceNumber: "0010",
    total: 650,
    splitCost: 81.25,
    invoiceDueDate: "2023-11-30",
    invoiceTitle: "Repaired Gate Cable",
    status: "Unpaid",
  },
  {
    id: "7jNzHetAwKd2lmxh2eYb",
    splitCost: 0,
    status: "Paid",
    batchNumber: 13,
    total: 33248.8,
    list: [
      {
        amount: "4156.10",
        description: "EC Security - February Invoice",
        quantity: "1",
      },
    ],
    invoiceNumber: "0013",
    invoiceDueDate: "2024-01-31",
    invoiceTitle: "EC Security - February Invoice",
    invoiceDate: "2024-01-16",
    complexName: "Yale",
  },
  {
    id: "80Ofj0DYSZddxFev8ryL",
    total: 9504,
    invoiceTitle: "Princeton Reimbursement for Greenbelt Cutting",
    splitCost: 1188,
    batchNumber: 6,
    invoiceDueDate: "2023-10-31",
    invoiceDate: "2023-10-11",
    complexName: "Princeton",
    status: "Unpaid",
    list: [
      {
        description:
          "10M CUTTING THE TREES INCLUDING MACHINE AND LABOUR (DAVID TLB)",
        amount: "500",
        quantity: "1",
      },
      {
        amount: "688",
        quantity: "1",
        description:
          "Removing of, cutting & cleaning (veld) at the back of Princeton",
      },
    ],
    invoiceNumber: "0006",
  },
  {
    id: "8CPRuFQq7ppOQCi0FKNN",
    status: "Paid",
    total: 2504,
    invoiceTitle: "2022 Annual Intercom Fee",
    invoiceDate: "2023-09-21",
    complexName: "NYU",
    list: [
      {
        description: "2022 Annual Intercom Fee Contribution",
        quantity: "1",
        amount: "313",
      },
    ],
    splitCost: 0,
    invoiceNumber: "0005",
    invoiceDueDate: "2023-09-30",
    batchNumber: 5,
  },
  {
    id: "8J9hLR8zIunoCDkLRx7C",
    invoiceNumber: "0014",
    status: "Paid",
    list: [
      {
        amount: "4156.10",
        description: "EC Security - March Invoice",
        quantity: "1",
      },
    ],
    total: 33248.8,
    batchNumber: 14,
    invoiceTitle: "EC Security - March Invoice",
    splitCost: 0,
    invoiceDate: "2024-02-26",
    complexName: "UCLA",
    invoiceDueDate: "2024-03-04",
  },
  {
    id: "9oioikDxcPThrwab85Od",
    invoiceDate: "2023-08-25",
    splitCost: 0,
    status: "Paid",
    list: [
      {
        amount: "313",
        quantity: "1",
        description: "Main Gate Intercom Annual Fee Contribution",
      },
    ],
    paidAmount: 313,
    invoiceNumber: "0004",
    datePaid: "2023-08-31",
    total: 2504,
    invoiceDueDate: "2023-08-31",
    complexName: "Cambridge",
    batchNumber: 4,
    invoiceTitle:
      "The Campus Complex Intercom - Request for Payment Instructions and Invoice",
  },
  {
    id: "AYhenx6vkQWzNlhVZV9b",
    invoiceDueDate: "2023-09-30",
    invoiceTitle: "2022 Annual Intercom Fee",
    invoiceNumber: "0005",
    complexName: "UCLA",
    batchNumber: 5,
    status: "Paid",
    splitCost: 0,
    invoiceDate: "2023-09-21",
    list: [
      {
        description: "2022 Annual Intercom Fee Contribution",
        amount: "313",
        quantity: "1",
      },
    ],
    total: 2504,
  },
  {
    id: "B5f0LWFkGlRpofTAKAvI",
    status: "Paid",
    batchNumber: 9,
    invoiceDueDate: "2023-10-31",
    invoiceTitle: "Main Gate Power Supply Replacement",
    invoiceNumber: "0009",
    splitCost: 0,
    list: [
      {
        description: "Centurion D10 24v PSU + Call Out Fee",
        quantity: "1",
        amount: "195.50",
      },
    ],
    invoiceDate: "2023-10-25",
    complexName: "NYU",
    total: 1564,
  },
  {
    id: "BCz9tM0Db0843zcNhblq",
    paidAmount: 313,
    complexName: "Harvard",
    invoiceDate: "2023-08-25",
    invoiceNumber: "0004",
    datePaid: "2023-08-30",
    splitCost: 0,
    invoiceTitle:
      "The Campus Complex Intercom - Request for Payment Instructions and Invoice",
    total: 2504,
    batchNumber: 4,
    list: [
      {
        description: "Main Gate Intercom Annual Fee Contribution",
        quantity: "1",
        amount: "313",
      },
    ],
    invoiceDueDate: "2023-08-31",
    status: "Paid",
  },
  {
    id: "BDzup6M2rinZ8UflwYFs",
    invoiceDate: "2024-02-26",
    batchNumber: 14,
    invoiceDueDate: "2024-03-04",
    list: [
      {
        quantity: "1",
        amount: "4156.10",
        description: "EC Security - March Invoice",
      },
    ],
    splitCost: 0,
    total: 33248.8,
    complexName: "NYU",
    status: "Paid",
    invoiceTitle: "EC Security - March Invoice",
    invoiceNumber: "0014",
  },
  {
    id: "BWIhGxZFkNVmKyuiXC8W",
    batchNumber: 10,
    total: 650,
    invoiceTitle: "Repaired Gate Cable",
    complexName: "Stanford",
    splitCost: 0,
    status: "Paid",
    invoiceNumber: "0010",
    invoiceDueDate: "2023-11-30",
    invoiceDate: "2023-11-06",
    list: [
      {
        amount: "81.25",
        description: "Trace and Repair of Damaged Cable",
        quantity: "1",
      },
    ],
  },
  {
    id: "C3T8Isgm0eDFlKQNlT3O",
    invoiceDate: "2023-09-21",
    list: [
      {
        description: "2022 Annual Intercom Fee Contribution",
        amount: "313",
        quantity: "1",
      },
    ],
    status: "Paid",
    invoiceNumber: "0005",
    invoiceDueDate: "2023-09-30",
    total: 2504,
    invoiceTitle: "2022 Annual Intercom Fee",
    splitCost: 0,
    batchNumber: 5,
    complexName: "Harvard",
  },
  {
    id: "CEo3hxIX19wgzNN97i9J",
    invoiceDueDate: "2024-03-04",
    invoiceTitle: "EC Security - March Invoice",
    batchNumber: 14,
    status: "Paid",
    invoiceNumber: "0014",
    complexName: "Cambridge",
    total: 33248.8,
    list: [
      {
        description: "EC Security - March Invoice",
        amount: "4156.10",
        quantity: "1",
      },
    ],
    splitCost: 0,
    invoiceDate: "2024-02-26",
  },
  {
    id: "D7wrYnfdIWgTbqJDsJNI",
    total: 1568,
    invoiceNumber: "0001",
    invoiceTitle:
      "Gate Wheels Replacement, Rack Adjustment & Pinion Gear Replacement.",
    complexName: "Cambridge",
    list: [
      {
        quantity: "1",
        description:
          "Gate Wheels Replacement, Rack Adjustment & Pinion Gear Replacement.",
        amount: "196",
      },
    ],
    status: "Paid",
    invoiceDate: "2023-06-10",
    batchNumber: 1,
    splitCost: 0,
    invoiceDueDate: "2023-06-30",
  },
  {
    id: "DSCcGfuUIsfFbEEOrc2K",
    splitCost: 0,
    batchNumber: 5,
    complexName: "Princeton",
    invoiceDueDate: "2023-09-30",
    invoiceNumber: "0005",
    total: 2504,
    status: "Paid",
    invoiceTitle: "2022 Annual Intercom Fee",
    invoiceDate: "2023-09-21",
    list: [
      {
        quantity: "1",
        amount: "313",
        description: "2022 Annual Intercom Fee Contribution",
      },
    ],
  },
  {
    id: "EILGU20h9Q2gx5ABnaCN",
    invoiceTitle: "Main Gate Power Supply Replacement",
    invoiceDate: "2023-10-25",
    batchNumber: 9,
    total: 1564,
    invoiceDueDate: "2023-10-31",
    status: "Paid",
    complexName: "Cambridge",
    splitCost: 0,
    list: [
      {
        amount: "195.50",
        description: "Centurion D10 24v PSU + Call Out Fee",
        quantity: "1",
      },
    ],
    invoiceNumber: "0009",
  },
  {
    id: "EkSBF2sX5fj9ggROWypw",
    invoiceNumber: "0006",
    invoiceDate: "2023-10-11",
    invoiceTitle: "Princeton Reimbursement for Greenbelt Cutting",
    total: 9504,
    batchNumber: 6,
    status: "Unpaid",
    list: [
      {
        quantity: "1",
        description:
          "10M CUTTING THE TREES INCLUDING MACHINE AND LABOUR (DAVID TLB)",
        amount: "500",
      },
      {
        amount: "688",
        description:
          "Removing of, cutting & cleaning (veld) at the back of Princeton",
        quantity: "1",
      },
    ],
    complexName: "Harvard",
    invoiceDueDate: "2023-10-31",
    splitCost: 1188,
  },
  {
    id: "GEvb84uO2B1OqNlXTZlc",
    invoiceNumber: "0013",
    status: "Paid",
    splitCost: 0,
    invoiceTitle: "EC Security - February Invoice",
    list: [
      {
        quantity: "1",
        description: "EC Security - February Invoice",
        amount: "4156.10",
      },
    ],
    total: 33248.8,
    complexName: "Harvard",
    invoiceDate: "2024-01-16",
    invoiceDueDate: "2024-01-31",
    batchNumber: 13,
  },
  {
    id: "I3MVDYCGXXUaC82XTF9m",
    splitCost: 1188,
    batchNumber: 6,
    invoiceDate: "2023-10-11",
    total: 9504,
    invoiceNumber: "0006",
    list: [
      {
        amount: "500",
        description:
          "10M CUTTING THE TREES INCLUDING MACHINE AND LABOUR (DAVID TLB)",
        quantity: "1",
      },
      {
        description:
          "Removing of, cutting & cleaning (veld) at the back of Princeton",
        amount: "688",
        quantity: "1",
      },
    ],
    invoiceDueDate: "2023-10-31",
    status: "Unpaid",
    complexName: "Cambridge",
    invoiceTitle: "Princeton Reimbursement for Greenbelt Cutting",
  },
  {
    id: "IcH4keFeIHZsHfVWIiNS",
    complexName: "Yale",
    batchNumber: 8,
    invoiceDate: "2023-10-25",
    status: "Paid",
    total: 900,
    invoiceNumber: "0008",
    invoiceTitle: "Remote Programming - Main Gate",
    invoiceDueDate: "2023-10-31",
    list: [
      {
        description:
          "Bentley Security Services - Remote Reprogramming Call Out Fee",
        amount: "112.50",
        quantity: "1",
      },
    ],
    splitCost: 0,
  },
  {
    id: "JOjpOShZoZxxox46iXjQ",
    list: [
      {
        description: "EC Security - March Invoice",
        amount: "4156.10",
        quantity: "1",
      },
    ],
    invoiceTitle: "EC Security - March Invoice",
    batchNumber: 14,
    invoiceDueDate: "2024-03-04",
    invoiceNumber: "0014",
    complexName: "Stanford",
    status: "Paid",
    invoiceDate: "2024-02-26",
    splitCost: 0,
    total: 33248.8,
  },
  {
    id: "JZ28n3efHMugkUZN02Mt",
    splitCost: 0,
    complexName: "Yale",
    total: 3200,
    invoiceDate: "2023-10-11",
    list: [
      {
        amount: "400",
        quantity: "1",
        description: "The Campus Main Gate Intercom Contribution 2022",
      },
    ],
    invoiceDueDate: "2023-10-31",
    status: "Paid",
    invoiceNumber: "0007",
    batchNumber: 7,
    invoiceTitle: "The Campus - Main Gate Intercom Fee 2022",
  },
  {
    id: "JydlmKLsy4qZew8JeRAC",
    invoiceDueDate: "2023-11-30",
    status: "Unpaid",
    batchNumber: 10,
    complexName: "Princeton",
    list: [
      {
        description: "Trace and Repair of Damaged Cable",
        quantity: "1",
        amount: "81.25",
      },
    ],
    splitCost: 81.25,
    invoiceTitle: "Repaired Gate Cable",
    invoiceDate: "2023-11-06",
    invoiceNumber: "0010",
    total: 650,
  },
  {
    id: "KZoFFMAGcRwcsInZ3M2m",
    invoiceDueDate: "2023-09-30",
    status: "Paid",
    complexName: "Stanford",
    splitCost: 0,
    invoiceNumber: "0005",
    total: 2504,
    list: [
      {
        amount: "313",
        quantity: "1",
        description: "2022 Annual Intercom Fee Contribution",
      },
    ],
    invoiceTitle: "2022 Annual Intercom Fee",
    invoiceDate: "2023-09-21",
    batchNumber: 5,
  },
  {
    id: "LSmMw40rhC4qhgnYP7pM",
    invoiceNumber: "0013",
    splitCost: 0,
    invoiceDate: "2024-01-16",
    invoiceDueDate: "2024-01-31",
    batchNumber: 13,
    total: 33248.8,
    list: [
      {
        amount: "4156.10",
        description: "EC Security - February Invoice",
        quantity: "1",
      },
    ],
    complexName: "Oxford",
    invoiceTitle: "EC Security - February Invoice",
    status: "Paid",
  },
  {
    id: "N4O6rbfOWKejoSt1Yv4z",
    invoiceDueDate: "2023-10-31",
    invoiceNumber: "0007",
    batchNumber: 7,
    total: 3200,
    invoiceDate: "2023-10-11",
    splitCost: 0,
    status: "Paid",
    list: [
      {
        amount: "400",
        description: "The Campus Main Gate Intercom Contribution 2022",
        quantity: "1",
      },
    ],
    complexName: "Princeton",
    invoiceTitle: "The Campus - Main Gate Intercom Fee 2022",
  },
  {
    id: "NWKC1ECvfbOtJTZtubQt",
    invoiceTitle: "Remote Reprogramming + Airtime Contribution",
    invoiceDueDate: "2023-07-31",
    invoiceNumber: "0002",
    batchNumber: 2,
    list: [
      {
        quantity: "1",
        description:
          "Call Out Fee for Remote Programming - 2 Dates & Overtime. 13 th June 10:00 - 12:00 & 18 th June 18:30 - 19:30",
        amount: "143.75",
      },
      {
        quantity: "1",
        description: "Main Gate Intercom Monthly Airtime Contribution ",
        amount: "200",
      },
      {
        quantity: "1",
        amount: "33.13",
        description:
          "UCLA Main Gate Intercom Reimbursement (R265- 1x R110 Airtime + 1x 200 SMS's)",
      },
      {
        description:
          "Princeton Main Gate Intercom Reimbursement (R245 - 1x R200 Airtime + 1x 200 SMS's)",
        amount: "30.63",
        quantity: "1",
      },
    ],
    total: 3260.08,
    complexName: "Cambridge",
    invoiceDate: "2023-07-16",
    status: "Unpaid",
    splitCost: 407.51,
  },
  {
    id: "NbPiL2yBufkADIfvfouq",
    invoiceDueDate: "2024-01-31",
    batchNumber: 12,
    list: [
      {
        amount: "4256.72",
        description: "Harvard Reimbursement- EC December",
        quantity: "1",
      },
    ],
    complexName: "Princeton",
    invoiceNumber: "0012",
    invoiceDate: "2024-01-11",
    total: 34053.76,
    splitCost: 4256.72,
    invoiceTitle: "Harvard Reimbursement- EC December",
    status: "Unpaid",
  },
  {
    id: "QIRJKNeCTgbd3gkBNKAE",
    invoiceDate: "2023-11-06",
    splitCost: 81.25,
    batchNumber: 10,
    invoiceNumber: "0010",
    total: 650,
    status: "Unpaid",
    complexName: "NYU",
    invoiceTitle: "Repaired Gate Cable",
    list: [
      {
        description: "Trace and Repair of Damaged Cable",
        amount: "81.25",
        quantity: "1",
      },
    ],
    invoiceDueDate: "2023-11-30",
  },
  {
    id: "RaFeAtFKxg1z1QsT6Igr",
    invoiceDueDate: "2023-08-31",
    status: "Paid",
    invoiceDate: "2023-08-25",
    total: 2504,
    list: [
      {
        description: "Main Gate Intercom Annual Fee Contribution",
        amount: "313",
        quantity: "1",
      },
    ],
    invoiceNumber: "0004",
    batchNumber: 4,
    complexName: "NYU",
    invoiceTitle:
      "The Campus Complex Intercom - Request for Payment Instructions and Invoice",
    splitCost: 0,
  },
  {
    id: "S6AsoavSLxpTkoTsMYAF",
    invoiceTitle: "EC Security ",
    invoiceNumber: "0011",
    batchNumber: 11,
    total: 33991.44,
    splitCost: 4248.93,
    invoiceDate: "2023-11-27",
    invoiceDueDate: "2023-11-30",
    complexName: "Oxford",
    status: "Unpaid",
    list: [
      {
        quantity: "1",
        amount: "4248.93",
        description: "EC Security - Main Gate Guarding ",
      },
    ],
  },
  {
    id: "SNLUabLQhhL7tKWxGG19",
    status: "Unpaid",
    invoiceDueDate: "2023-11-30",
    list: [
      {
        description: "Trace and Repair of Damaged Cable",
        amount: "81.25",
        quantity: "1",
      },
    ],
    invoiceDate: "2023-11-06",
    invoiceNumber: "0010",
    splitCost: 81.25,
    batchNumber: 10,
    total: 650,
    invoiceTitle: "Repaired Gate Cable",
    complexName: "Yale",
  },
  {
    id: "SP0KRy9nBGXHKoDrKMnq",
    invoiceDate: "2023-06-10",
    batchNumber: 1,
    list: [
      {
        description:
          "Gate Wheels Replacement, Rack Adjustment & Pinion Gear Replacement.",
        quantity: "1",
        amount: "196",
      },
    ],
    invoiceNumber: "0001",
    complexName: "Yale",
    invoiceTitle:
      "Gate Wheels Replacement, Rack Adjustment & Pinion Gear Replacement.",
    invoiceDueDate: "2023-06-30",
    total: 1568,
    splitCost: 0,
    status: "Paid",
  },
  {
    id: "TWu9rLYskLsrzfYmRC9t",
    invoiceDueDate: "2023-10-31",
    total: 9504,
    status: "Paid",
    splitCost: 0,
    complexName: "Yale",
    invoiceDate: "2023-10-11",
    batchNumber: 6,
    invoiceNumber: "0006",
    invoiceTitle: "Princeton Reimbursement for Greenbelt Cutting",
    list: [
      {
        quantity: "1",
        description:
          "10M CUTTING THE TREES INCLUDING MACHINE AND LABOUR (DAVID TLB)",
        amount: "500",
      },
      {
        quantity: "1",
        description:
          "Removing of, cutting & cleaning (veld) at the back of Princeton",
        amount: "688",
      },
    ],
  },
  {
    id: "Uz1xmxymXiKu75tcOv4q",
    list: [
      {
        quantity: "1",
        amount: "4248.93",
        description: "EC Security - Main Gate Guarding ",
      },
    ],
    invoiceDate: "2023-11-27",
    total: 33991.44,
    complexName: "Stanford",
    splitCost: 4248.93,
    status: "Unpaid",
    invoiceTitle: "EC Security ",
    batchNumber: 11,
    invoiceDueDate: "2023-11-30",
    invoiceNumber: "0011",
  },
  {
    id: "WhKI4rv1fd4NZiM1Nx9J",
    invoiceNumber: "0002",
    complexName: "Princeton",
    invoiceTitle: "Remote Reprogramming + Airtime Contribution",
    batchNumber: 2,
    invoiceDueDate: "2023-07-31",
    list: [
      {
        description:
          "Call Out Fee for Remote Programming - 2 Dates & Overtime. 13 th June 10:00 - 12:00 & 18 th June 18:30 - 19:30",
        amount: "143.75",
        quantity: "1",
      },
      {
        description: "Main Gate Intercom Monthly Airtime Contribution ",
        amount: "200",
        quantity: "1",
      },
      {
        quantity: "1",
        amount: "33.13",
        description:
          "UCLA Main Gate Intercom Reimbursement (R265- 1x R110 Airtime + 1x 200 SMS's)",
      },
      {
        quantity: "1",
        description:
          "Princeton Main Gate Intercom Reimbursement (R245 - 1x R200 Airtime + 1x 200 SMS's)",
        amount: "30.63",
      },
    ],
    splitCost: 0,
    status: "Paid",
    total: 3260.08,
    invoiceDate: "2023-07-16",
  },
  {
    id: "WhneOssx3L0mG21ooZlA",
    list: [
      {
        quantity: "1",
        description: "EC Security - February Invoice",
        amount: "4156.10",
      },
    ],
    invoiceDate: "2024-01-16",
    batchNumber: 13,
    status: "Paid",
    invoiceNumber: "0013",
    invoiceDueDate: "2024-01-31",
    complexName: "UCLA",
    splitCost: 0,
    invoiceTitle: "EC Security - February Invoice",
    total: 33248.8,
  },
  {
    id: "WifoKkyLAdvy2YDgOved",
    complexName: "Cambridge",
    status: "Paid",
    invoiceNumber: "0003",
    list: [
      {
        amount: "167",
        description: "Gate Wheels Replacement & Rack Adjustment Exit Gate",
        quantity: "1",
      },
      {
        description:
          "Princeton Main Gate Intercom Reimbursement (R245 - 1x R200 Airtime + 1x 200 SMS's)",
        quantity: "1",
        amount: "31",
      },
    ],
    invoiceTitle:
      "Gate Wheels Replacement & Rack Adjustment Exit Gate + Intercom Airtime Reimbursement",
    invoiceDate: "2023-08-24",
    batchNumber: 3,
    splitCost: 0,
    invoiceDueDate: "2023-08-31",
    total: 1584,
  },
  {
    id: "XByF13QOB5yOOtHp6Luv",
    total: 3260.08,
    invoiceDate: "2023-07-16",
    splitCost: 0,
    invoiceDueDate: "2023-07-31",
    invoiceNumber: "0002",
    list: [
      {
        amount: "143.75",
        quantity: "1",
        description:
          "Call Out Fee for Remote Programming - 2 Dates & Overtime. 13 th June 10:00 - 12:00 & 18 th June 18:30 - 19:30",
      },
      {
        amount: "200",
        description: "Main Gate Intercom Monthly Airtime Contribution ",
        quantity: "1",
      },
      {
        quantity: "1",
        description:
          "UCLA Main Gate Intercom Reimbursement (R265- 1x R110 Airtime + 1x 200 SMS's)",
        amount: "33.13",
      },
      {
        quantity: "1",
        description:
          "Princeton Main Gate Intercom Reimbursement (R245 - 1x R200 Airtime + 1x 200 SMS's)",
        amount: "30.63",
      },
    ],
    status: "Paid",
    batchNumber: 2,
    invoiceTitle: "Remote Reprogramming + Airtime Contribution",
    complexName: "Harvard",
  },
  {
    id: "XOClfIhajU4oavybEVOS",
    list: [
      {
        amount: "196",
        description:
          "Gate Wheels Replacement, Rack Adjustment & Pinion Gear Replacement.",
        quantity: "1",
      },
    ],
    invoiceTitle:
      "Gate Wheels Replacement, Rack Adjustment & Pinion Gear Replacement.",
    splitCost: 0,
    status: "Paid",
    invoiceNumber: "0001",
    invoiceDueDate: "2023-06-30",
    total: 1568,
    invoiceDate: "2023-06-10",
    batchNumber: 1,
    complexName: "Stanford",
  },
  {
    id: "XlBNLQA03vUFXTwOG9Au",
    batchNumber: 11,
    list: [
      {
        quantity: "1",
        amount: "4248.93",
        description: "EC Security - Main Gate Guarding ",
      },
    ],
    invoiceDate: "2023-11-27",
    total: 33991.44,
    status: "Unpaid",
    splitCost: 4248.93,
    complexName: "Princeton",
    invoiceDueDate: "2023-11-30",
    invoiceTitle: "EC Security ",
    invoiceNumber: "0011",
  },
  {
    id: "YSRg1l4FeMoCakcNwlnh",
    invoiceDueDate: "2023-10-31",
    batchNumber: 8,
    list: [
      {
        quantity: "1",
        amount: "112.50",
        description:
          "Bentley Security Services - Remote Reprogramming Call Out Fee",
      },
    ],
    invoiceDate: "2023-10-25",
    invoiceNumber: "0008",
    invoiceTitle: "Remote Programming - Main Gate",
    complexName: "UCLA",
    total: 900,
    status: "Unpaid",
    splitCost: 112.5,
  },
  {
    id: "YlSWztBh29iahMeDBqmw",
    invoiceDate: "2023-08-25",
    invoiceDueDate: "2023-08-31",
    total: 2504,
    status: "Unpaid",
    batchNumber: 4,
    invoiceTitle:
      "The Campus Complex Intercom - Request for Payment Instructions and Invoice",
    complexName: "Oxford",
    splitCost: 313,
    list: [
      {
        description: "Main Gate Intercom Annual Fee Contribution",
        quantity: "1",
        amount: "313",
      },
    ],
    invoiceNumber: "0004",
  },
  {
    id: "YmlK9UxL4bsFwSMxFysv",
    invoiceDueDate: "2023-06-30",
    complexName: "Harvard",
    invoiceNumber: "0001",
    list: [
      {
        description:
          "Gate Wheels Replacement, Rack Adjustment & Pinion Gear Replacement.",
        quantity: "1",
        amount: "196",
      },
    ],
    invoiceDate: "2023-06-10",
    invoiceTitle:
      "Gate Wheels Replacement, Rack Adjustment & Pinion Gear Replacement.",
    total: 1568,
    batchNumber: 1,
    splitCost: 0,
    status: "Paid",
  },
  {
    id: "ZGBHVIcjylJoUAYYG1xi",
    complexName: "UCLA",
    invoiceTitle: "Repaired Gate Cable",
    splitCost: 81.25,
    batchNumber: 10,
    list: [
      {
        description: "Trace and Repair of Damaged Cable",
        amount: "81.25",
        quantity: "1",
      },
    ],
    invoiceDate: "2023-11-06",
    total: 650,
    invoiceNumber: "0010",
    status: "Unpaid",
    invoiceDueDate: "2023-11-30",
  },
  {
    id: "ZoE1V51qrQAZz1aNJDYx",
    total: 1564,
    batchNumber: 9,
    list: [
      {
        amount: "195.50",
        description: "Centurion D10 24v PSU + Call Out Fee",
        quantity: "1",
      },
    ],
    invoiceDate: "2023-10-25",
    status: "Unpaid",
    splitCost: 195.5,
    invoiceTitle: "Main Gate Power Supply Replacement",
    complexName: "Oxford",
    invoiceNumber: "0009",
    invoiceDueDate: "2023-10-31",
  },
  {
    id: "ZqQOe6To5QSeaAkHs76e",
    invoiceTitle:
      "Gate Wheels Replacement & Rack Adjustment Exit Gate + Intercom Airtime Reimbursement",
    list: [
      {
        description: "Gate Wheels Replacement & Rack Adjustment Exit Gate",
        amount: "167",
        quantity: "1",
      },
      {
        description:
          "Princeton Main Gate Intercom Reimbursement (R245 - 1x R200 Airtime + 1x 200 SMS's)",
        amount: "31",
        quantity: "1",
      },
    ],
    invoiceDate: "2023-08-24",
    total: 1584,
    invoiceDueDate: "2023-08-31",
    invoiceNumber: "0003",
    splitCost: 0,
    complexName: "Stanford",
    status: "Paid",
    batchNumber: 3,
  },
  {
    id: "aSzamJYa0X0uuDakGGcE",
    status: "Paid",
    invoiceTitle:
      "Gate Wheels Replacement, Rack Adjustment & Pinion Gear Replacement.",
    batchNumber: 1,
    invoiceDueDate: "2023-06-30",
    splitCost: 0,
    invoiceNumber: "0001",
    list: [
      {
        description:
          "Gate Wheels Replacement, Rack Adjustment & Pinion Gear Replacement.",
        amount: "196",
        quantity: "1",
      },
    ],
    total: 1568,
    invoiceDate: "2023-06-10",
    complexName: "Princeton",
  },
  {
    id: "aThJBQ2HQFgK4FYRylTX",
    invoiceNumber: "0010",
    invoiceTitle: "Repaired Gate Cable",
    invoiceDate: "2023-11-06",
    complexName: "Harvard",
    status: "Paid",
    batchNumber: 10,
    list: [
      {
        description: "Trace and Repair of Damaged Cable",
        quantity: "1",
        amount: "81.25",
      },
    ],
    total: 650,
    invoiceDueDate: "2023-11-30",
    splitCost: 0,
  },
  {
    id: "b1sCFca8CsZ8bPNjob53",
    complexName: "Harvard",
    list: [
      {
        description: "EC Security - March Invoice",
        amount: "4156.10",
        quantity: "1",
      },
    ],
    invoiceDueDate: "2024-03-04",
    splitCost: 0,
    batchNumber: 14,
    invoiceNumber: "0014",
    invoiceDate: "2024-02-26",
    status: "Paid",
    invoiceTitle: "EC Security - March Invoice",
    total: 33248.8,
  },
  {
    id: "bGha0EXHdXklVQENznDJ",
    invoiceNumber: "0005",
    invoiceTitle: "2022 Annual Intercom Fee",
    total: 2504,
    batchNumber: 5,
    complexName: "Cambridge",
    invoiceDate: "2023-09-21",
    splitCost: 313,
    invoiceDueDate: "2023-09-30",
    status: "Unpaid",
    list: [
      {
        description: "2022 Annual Intercom Fee Contribution",
        amount: "313",
        quantity: "1",
      },
    ],
  },
  {
    id: "buXFLc5ZSBxQ9d5mYzd5",
    batchNumber: 11,
    invoiceNumber: "0011",
    list: [
      {
        description: "EC Security - Main Gate Guarding ",
        amount: "4248.93",
        quantity: "1",
      },
    ],
    invoiceTitle: "EC Security ",
    total: 33991.44,
    splitCost: 4248.93,
    complexName: "Yale",
    status: "Unpaid",
    invoiceDueDate: "2023-11-30",
    invoiceDate: "2023-11-27",
  },
  {
    id: "cUVq7XwoZSp3ItWfdIlt",
    invoiceNumber: "0002",
    invoiceDueDate: "2023-07-31",
    status: "Unpaid",
    invoiceTitle: "Remote Reprogramming + Airtime Contribution",
    batchNumber: 2,
    invoiceDate: "2023-07-16",
    complexName: "NYU",
    splitCost: 407.51,
    total: 3260.08,
    list: [
      {
        amount: "143.75",
        description:
          "Call Out Fee for Remote Programming - 2 Dates & Overtime. 13 th June 10:00 - 12:00 & 18 th June 18:30 - 19:30",
        quantity: "1",
      },
      {
        amount: "200",
        quantity: "1",
        description: "Main Gate Intercom Monthly Airtime Contribution ",
      },
      {
        amount: "33.13",
        quantity: "1",
        description:
          "UCLA Main Gate Intercom Reimbursement (R265- 1x R110 Airtime + 1x 200 SMS's)",
      },
      {
        amount: "30.63",
        quantity: "1",
        description:
          "Princeton Main Gate Intercom Reimbursement (R245 - 1x R200 Airtime + 1x 200 SMS's)",
      },
    ],
  },
  {
    id: "ckdlERga4qHRhIMAPSBF",
    list: [
      {
        amount: "167",
        quantity: "1",
        description: "Gate Wheels Replacement & Rack Adjustment Exit Gate",
      },
      {
        description:
          "Princeton Main Gate Intercom Reimbursement (R245 - 1x R200 Airtime + 1x 200 SMS's)",
        amount: "31",
        quantity: "1",
      },
    ],
    total: 1584,
    status: "Paid",
    invoiceNumber: "0003",
    invoiceDueDate: "2023-08-31",
    invoiceDate: "2023-08-24",
    splitCost: 0,
    invoiceTitle:
      "Gate Wheels Replacement & Rack Adjustment Exit Gate + Intercom Airtime Reimbursement",
    batchNumber: 3,
    complexName: "Yale",
  },
  {
    id: "cqcF3CqNAAw9yX1fZ5O8",
    splitCost: 0,
    invoiceDueDate: "2023-07-31",
    invoiceDate: "2023-07-16",
    invoiceNumber: "0002",
    status: "Paid",
    complexName: "Stanford",
    invoiceTitle: "Remote Reprogramming + Airtime Contribution",
    batchNumber: 2,
    total: 3260.08,
    list: [
      {
        amount: "143.75",
        description:
          "Call Out Fee for Remote Programming - 2 Dates & Overtime. 13 th June 10:00 - 12:00 & 18 th June 18:30 - 19:30",
        quantity: "1",
      },
      {
        description: "Main Gate Intercom Monthly Airtime Contribution ",
        amount: "200",
        quantity: "1",
      },
      {
        quantity: "1",
        description:
          "UCLA Main Gate Intercom Reimbursement (R265- 1x R110 Airtime + 1x 200 SMS's)",
        amount: "33.13",
      },
      {
        quantity: "1",
        amount: "30.63",
        description:
          "Princeton Main Gate Intercom Reimbursement (R245 - 1x R200 Airtime + 1x 200 SMS's)",
      },
    ],
  },
  {
    id: "czvl6Vqqx08FoNJnjQ4w",
    invoiceDueDate: "2023-10-31",
    complexName: "UCLA",
    list: [
      {
        quantity: "1",
        description: "Centurion D10 24v PSU + Call Out Fee",
        amount: "195.50",
      },
    ],
    invoiceTitle: "Main Gate Power Supply Replacement",
    status: "Paid",
    total: 1564,
    batchNumber: 9,
    invoiceNumber: "0009",
    splitCost: 0,
    invoiceDate: "2023-10-25",
  },
  {
    id: "d1puIJGoqYi8M07NqkBP",
    total: 33248.8,
    invoiceDueDate: "2024-01-31",
    status: "Paid",
    batchNumber: 13,
    invoiceNumber: "0013",
    list: [
      {
        quantity: "1",
        description: "EC Security - February Invoice",
        amount: "4156.10",
      },
    ],
    invoiceDate: "2024-01-16",
    complexName: "Cambridge",
    splitCost: 0,
    invoiceTitle: "EC Security - February Invoice",
  },
  {
    id: "fIRqwgTKy7dxnGKuYzjv",
    invoiceNumber: "0009",
    splitCost: 0,
    list: [
      {
        quantity: "1",
        description: "Centurion D10 24v PSU + Call Out Fee",
        amount: "195.50",
      },
    ],
    status: "Paid",
    invoiceDueDate: "2023-10-31",
    invoiceDate: "2023-10-25",
    batchNumber: 9,
    invoiceTitle: "Main Gate Power Supply Replacement",
    total: 1564,
    complexName: "Princeton",
  },
  {
    id: "fUFOSMTF0AMzmoZySIvo",
    splitCost: 0,
    invoiceDate: "2023-07-16",
    invoiceDueDate: "2023-07-31",
    invoiceNumber: "0002",
    complexName: "Oxford",
    batchNumber: 2,
    status: "Paid",
    total: 3260.08,
    invoiceTitle: "Remote Reprogramming + Airtime Contribution",
    list: [
      {
        description:
          "Call Out Fee for Remote Programming - 2 Dates & Overtime. 13 th June 10:00 - 12:00 & 18 th June 18:30 - 19:30",
        quantity: "1",
        amount: "143.75",
      },
      {
        quantity: "1",
        amount: "200",
        description: "Main Gate Intercom Monthly Airtime Contribution ",
      },
      {
        amount: "33.13",
        description:
          "UCLA Main Gate Intercom Reimbursement (R265- 1x R110 Airtime + 1x 200 SMS's)",
        quantity: "1",
      },
      {
        quantity: "1",
        description:
          "Princeton Main Gate Intercom Reimbursement (R245 - 1x R200 Airtime + 1x 200 SMS's)",
        amount: "30.63",
      },
    ],
  },
  {
    id: "gaXmJyH32jk7aEHW6yIk",
    splitCost: 0,
    invoiceTitle:
      "Gate Wheels Replacement & Rack Adjustment Exit Gate + Intercom Airtime Reimbursement",
    batchNumber: 3,
    invoiceNumber: "0003",
    invoiceDate: "2023-08-24",
    status: "Paid",
    invoiceDueDate: "2023-08-31",
    list: [
      {
        quantity: "1",
        amount: "167",
        description: "Gate Wheels Replacement & Rack Adjustment Exit Gate",
      },
      {
        description:
          "Princeton Main Gate Intercom Reimbursement (R245 - 1x R200 Airtime + 1x 200 SMS's)",
        quantity: "1",
        amount: "31",
      },
    ],
    total: 1584,
    complexName: "Harvard",
  },
  {
    id: "geYect8ziFQGB64v9KEz",
    complexName: "Oxford",
    batchNumber: 6,
    invoiceDueDate: "2023-10-31",
    invoiceNumber: "0006",
    list: [
      {
        description:
          "10M CUTTING THE TREES INCLUDING MACHINE AND LABOUR (DAVID TLB)",
        quantity: "1",
        amount: "500",
      },
      {
        description:
          "Removing of, cutting & cleaning (veld) at the back of Princeton",
        amount: "688",
        quantity: "1",
      },
    ],
    status: "Unpaid",
    invoiceDate: "2023-10-11",
    invoiceTitle: "Princeton Reimbursement for Greenbelt Cutting",
    total: 9504,
    splitCost: 1188,
  },
  {
    id: "i7dfDXcypNpl92t2p7y1",
    invoiceTitle: "EC Security ",
    list: [
      {
        description: "EC Security - Main Gate Guarding ",
        quantity: "1",
        amount: "4248.93",
      },
    ],
    complexName: "UCLA",
    total: 33991.44,
    batchNumber: 11,
    invoiceDueDate: "2023-11-30",
    splitCost: 4248.93,
    invoiceDate: "2023-11-27",
    status: "Unpaid",
    invoiceNumber: "0011",
  },
  {
    id: "joJIVwfI4YLujqBzc8SI",
    invoiceDueDate: "2023-10-31",
    total: 1564,
    splitCost: 0,
    invoiceNumber: "0009",
    complexName: "Stanford",
    list: [
      {
        amount: "195.50",
        description: "Centurion D10 24v PSU + Call Out Fee",
        quantity: "1",
      },
    ],
    invoiceDate: "2023-10-25",
    batchNumber: 9,
    invoiceTitle: "Main Gate Power Supply Replacement",
    status: "Paid",
  },
  {
    id: "l0jFwdKdMnW3wCDT3shh",
    batchNumber: 13,
    status: "Paid",
    total: 33248.8,
    splitCost: 0,
    invoiceNumber: "0013",
    invoiceDate: "2024-01-16",
    invoiceTitle: "EC Security - February Invoice",
    invoiceDueDate: "2024-01-31",
    complexName: "Princeton",
    list: [
      {
        quantity: "1",
        amount: "4156.10",
        description: "EC Security - February Invoice",
      },
    ],
  },
  {
    id: "lUy7FKBMwErjK0v17Ah0",
    status: "Unpaid",
    invoiceTitle: "Princeton Reimbursement for Greenbelt Cutting",
    batchNumber: 6,
    splitCost: 1188,
    list: [
      {
        description:
          "10M CUTTING THE TREES INCLUDING MACHINE AND LABOUR (DAVID TLB)",
        amount: "500",
        quantity: "1",
      },
      {
        amount: "688",
        description:
          "Removing of, cutting & cleaning (veld) at the back of Princeton",
        quantity: "1",
      },
    ],
    total: 9504,
    invoiceDueDate: "2023-10-31",
    complexName: "UCLA",
    invoiceDate: "2023-10-11",
    invoiceNumber: "0006",
  },
  {
    id: "mZY9QSX4mWylppEKoA24",
    invoiceNumber: "0005",
    invoiceTitle: "2022 Annual Intercom Fee",
    batchNumber: 5,
    invoiceDate: "2023-09-21",
    status: "Paid",
    splitCost: 0,
    total: 2504,
    complexName: "Yale",
    invoiceDueDate: "2023-09-30",
    list: [
      {
        description: "2022 Annual Intercom Fee Contribution",
        quantity: "1",
        amount: "313",
      },
    ],
  },
  {
    id: "mmIsXlPpiAU2Mq8yNhAk",
    invoiceTitle: "EC Security - March Invoice",
    batchNumber: 14,
    status: "Paid",
    invoiceDueDate: "2024-03-04",
    total: 33248.8,
    invoiceDate: "2024-02-26",
    splitCost: 0,
    complexName: "Princeton",
    list: [
      {
        quantity: "1",
        description: "EC Security - March Invoice",
        amount: "4156.10",
      },
    ],
    invoiceNumber: "0014",
  },
  {
    id: "nBHKAPaNLl2zyz3dtHpv",
    total: 2504,
    complexName: "Stanford",
    batchNumber: 4,
    splitCost: 0,
    invoiceDueDate: "2023-08-31",
    paidAmount: 313,
    datePaid: "2023-08-28",
    invoiceNumber: "0004",
    invoiceDate: "2023-08-25",
    invoiceTitle:
      "The Campus Complex Intercom - Request for Payment Instructions and Invoice",
    status: "Paid",
    list: [
      {
        quantity: "1",
        description: "Main Gate Intercom Annual Fee Contribution",
        amount: "313",
      },
    ],
  },
  {
    id: "pQ8ytBAPZYJMGrs0RXus",
    invoiceDueDate: "2023-07-31",
    list: [
      {
        amount: "143.75",
        description:
          "Call Out Fee for Remote Programming - 2 Dates & Overtime. 13 th June 10:00 - 12:00 & 18 th June 18:30 - 19:30",
        quantity: "1",
      },
      {
        description: "Main Gate Intercom Monthly Airtime Contribution ",
        amount: "200",
        quantity: "1",
      },
      {
        description:
          "UCLA Main Gate Intercom Reimbursement (R265- 1x R110 Airtime + 1x 200 SMS's)",
        amount: "33.13",
        quantity: "1",
      },
      {
        amount: "30.63",
        description:
          "Princeton Main Gate Intercom Reimbursement (R245 - 1x R200 Airtime + 1x 200 SMS's)",
        quantity: "1",
      },
    ],
    total: 3260.08,
    splitCost: 0,
    complexName: "UCLA",
    batchNumber: 2,
    invoiceNumber: "0002",
    invoiceDate: "2023-07-16",
    status: "Paid",
    invoiceTitle: "Remote Reprogramming + Airtime Contribution",
  },
  {
    id: "pk13leIu0DRJBn9UKMIh",
    invoiceDate: "2023-06-10",
    complexName: "NYU",
    total: 1568,
    list: [
      {
        amount: "196",
        quantity: "1",
        description:
          "Gate Wheels Replacement, Rack Adjustment & Pinion Gear Replacement.",
      },
    ],
    batchNumber: 1,
    invoiceNumber: "0001",
    splitCost: 196,
    status: "Unpaid",
    invoiceDueDate: "2023-06-30",
    invoiceTitle:
      "Gate Wheels Replacement, Rack Adjustment & Pinion Gear Replacement.",
  },
  {
    id: "pw0WsUZKm81dK0cn9WTF",
    complexName: "NYU",
    invoiceDate: "2024-01-16",
    total: 33248.8,
    invoiceDueDate: "2024-01-31",
    splitCost: 0,
    batchNumber: 13,
    status: "Paid",
    invoiceTitle: "EC Security - February Invoice",
    list: [
      {
        amount: "4156.10",
        quantity: "1",
        description: "EC Security - February Invoice",
      },
    ],
    invoiceNumber: "0013",
  },
  {
    id: "qxlHZV2r4QYIcKAlCZwL",
    splitCost: 0,
    invoiceDate: "2024-02-26",
    invoiceTitle: "EC Security - March Invoice",
    total: 33248.8,
    complexName: "Oxford",
    batchNumber: 14,
    status: "Paid",
    invoiceNumber: "0014",
    invoiceDueDate: "2024-03-04",
    list: [
      {
        description: "EC Security - March Invoice",
        quantity: "1",
        amount: "4156.10",
      },
    ],
  },
  {
    id: "rNMFJ3RH8h23ZMy6TnF1",
    status: "Paid",
    splitCost: 0,
    list: [
      {
        quantity: "1",
        description: "Gate Wheels Replacement & Rack Adjustment Exit Gate",
        amount: "167",
      },
      {
        description:
          "Princeton Main Gate Intercom Reimbursement (R245 - 1x R200 Airtime + 1x 200 SMS's)",
        quantity: "1",
        amount: "31",
      },
    ],
    invoiceDate: "2023-08-24",
    batchNumber: 3,
    invoiceNumber: "0003",
    complexName: "NYU",
    invoiceDueDate: "2023-08-31",
    total: 1584,
    invoiceTitle:
      "Gate Wheels Replacement & Rack Adjustment Exit Gate + Intercom Airtime Reimbursement",
  },
  {
    id: "rSsSwrBF9gcUCrfy3YHa",
    list: [
      {
        description: "Centurion D10 24v PSU + Call Out Fee",
        quantity: "1",
        amount: "195.50",
      },
    ],
    invoiceDueDate: "2023-10-31",
    invoiceTitle: "Main Gate Power Supply Replacement",
    complexName: "Harvard",
    status: "Paid",
    splitCost: 0,
    invoiceNumber: "0009",
    invoiceDate: "2023-10-25",
    total: 1564,
    batchNumber: 9,
  },
  {
    id: "sLSdAVrcUEX0vTBgUiXZ",
    invoiceDate: "2023-08-24",
    splitCost: 198,
    invoiceDueDate: "2023-08-31",
    complexName: "Oxford",
    batchNumber: 3,
    total: 1584,
    invoiceTitle:
      "Gate Wheels Replacement & Rack Adjustment Exit Gate + Intercom Airtime Reimbursement",
    list: [
      {
        quantity: "1",
        description: "Gate Wheels Replacement & Rack Adjustment Exit Gate",
        amount: "167",
      },
      {
        amount: "31",
        description:
          "Princeton Main Gate Intercom Reimbursement (R245 - 1x R200 Airtime + 1x 200 SMS's)",
        quantity: "1",
      },
    ],
    invoiceNumber: "0003",
    status: "Unpaid",
  },
  {
    id: "sU40r80Vvwk4wovY7ZTC",
    invoiceTitle:
      "The Campus Complex Intercom - Request for Payment Instructions and Invoice",
    total: 2504,
    status: "Paid",
    datePaid: "2023-09-06",
    invoiceDate: "2023-08-25",
    invoiceDueDate: "2023-08-31",
    splitCost: 0,
    paidAmount: 313,
    batchNumber: 4,
    complexName: "Princeton",
    list: [
      {
        amount: "313",
        description: "Main Gate Intercom Annual Fee Contribution",
        quantity: "1",
      },
    ],
    invoiceNumber: "0004",
  },
  {
    id: "umZOOmH4WN4CY28ctl0v",
    total: 33991.44,
    invoiceDueDate: "2023-11-30",
    invoiceTitle: "EC Security ",
    splitCost: 4248.93,
    complexName: "NYU",
    invoiceDate: "2023-11-27",
    invoiceNumber: "0011",
    list: [
      {
        amount: "4248.93",
        quantity: "1",
        description: "EC Security - Main Gate Guarding ",
      },
    ],
    batchNumber: 11,
    status: "Unpaid",
  },
  {
    id: "uwapceDHwQHagIOLA1tD",
    invoiceDate: "2023-09-21",
    invoiceTitle: "2022 Annual Intercom Fee",
    list: [
      {
        quantity: "1",
        description: "2022 Annual Intercom Fee Contribution",
        amount: "313",
      },
    ],
    complexName: "Oxford",
    invoiceNumber: "0005",
    invoiceDueDate: "2023-09-30",
    status: "Paid",
    total: 2504,
    batchNumber: 5,
    splitCost: 0,
  },
  {
    id: "v4K9kAEin4TkdShzJ6Vr",
    splitCost: 4248.93,
    complexName: "Harvard",
    list: [
      {
        description: "EC Security - Main Gate Guarding ",
        quantity: "1",
        amount: "4248.93",
      },
    ],
    total: 33991.44,
    invoiceDueDate: "2023-11-30",
    status: "Unpaid",
    batchNumber: 11,
    invoiceNumber: "0011",
    invoiceDate: "2023-11-27",
    invoiceTitle: "EC Security ",
  },
  {
    id: "vWnOU6mv9OXb7yWu7eiu",
    invoiceDueDate: "2023-06-30",
    invoiceDate: "2023-06-10",
    splitCost: 0,
    complexName: "UCLA",
    status: "Paid",
    batchNumber: 1,
    invoiceTitle:
      "Gate Wheels Replacement, Rack Adjustment & Pinion Gear Replacement.",
    invoiceNumber: "0001",
    list: [
      {
        quantity: "1",
        amount: "196",
        description:
          "Gate Wheels Replacement, Rack Adjustment & Pinion Gear Replacement.",
      },
    ],
    total: 1568,
  },
  {
    id: "wgMoyMGAjHDKRNQTuifI",
    splitCost: 0,
    complexName: "Stanford",
    total: 33248.8,
    invoiceTitle: "EC Security - February Invoice",
    batchNumber: 13,
    invoiceDueDate: "2024-01-31",
    invoiceNumber: "0013",
    status: "Paid",
    list: [
      {
        description: "EC Security - February Invoice",
        amount: "4156.10",
        quantity: "1",
      },
    ],
    invoiceDate: "2024-01-16",
  },
  {
    id: "wnRTiwUzikjvsGhRPmQi",
    invoiceTitle:
      "The Campus Complex Intercom - Request for Payment Instructions and Invoice",
    invoiceNumber: "0004",
    invoiceDueDate: "2023-08-31",
    complexName: "Yale",
    status: "Unpaid",
    splitCost: 313,
    total: 2504,
    batchNumber: 4,
    list: [
      {
        quantity: "1",
        amount: "313",
        description: "Main Gate Intercom Annual Fee Contribution",
      },
    ],
    invoiceDate: "2023-08-25",
  },
  {
    id: "xT0D3SiuQwwljXrt7jdi",
    total: 33248.8,
    batchNumber: 14,
    complexName: "Yale",
    list: [
      {
        description: "EC Security - March Invoice",
        quantity: "1",
        amount: "4156.10",
      },
    ],
    invoiceDate: "2024-02-26",
    invoiceDueDate: "2024-03-04",
    invoiceTitle: "EC Security - March Invoice",
    status: "Paid",
    invoiceNumber: "0014",
    splitCost: 0,
  },
  {
    id: "xcDhJXQdDXUtofsPT5zB",
    splitCost: 1188,
    total: 9504,
    invoiceDueDate: "2023-10-31",
    complexName: "NYU",
    invoiceDate: "2023-10-11",
    invoiceNumber: "0006",
    batchNumber: 6,
    list: [
      {
        description:
          "10M CUTTING THE TREES INCLUDING MACHINE AND LABOUR (DAVID TLB)",
        quantity: "1",
        amount: "500",
      },
      {
        quantity: "1",
        amount: "688",
        description:
          "Removing of, cutting & cleaning (veld) at the back of Princeton",
      },
    ],
    status: "Unpaid",
    invoiceTitle: "Princeton Reimbursement for Greenbelt Cutting",
  },
  {
    id: "yeVaAaal2WIj2zmAg9Pt",
    batchNumber: 8,
    splitCost: 0,
    invoiceDueDate: "2023-10-31",
    invoiceDate: "2023-10-25",
    complexName: "Stanford",
    invoiceTitle: "Remote Programming - Main Gate",
    invoiceNumber: "0008",
    list: [
      {
        description:
          "Bentley Security Services - Remote Reprogramming Call Out Fee",
        quantity: "1",
        amount: "112.50",
      },
    ],
    status: "Paid",
    total: 900,
  },
];
